---
- name: Install motion-Package
  apt:
    name: [ "motion", "ffmpeg", "v4l-utils", "python-pip", "python-dev", "python-setuptools", "python-pil", "curl", "libssl-dev", "libcurl4-openssl-dev", "libjpeg-dev", "libz-dev" ]
    state: present
    update_cache: no
  become: yes

- name: Install motioneye
  pip:
    name: 
      - motioneye
    executable: pip2
  become: yes