---
- name: restart motion-daemon
  systemd:
    name: motion
    daemon_reload: yes
    state: restarted
    enabled: yes
  become: yes
  ignore_errors: yes

- name: restart motioneye-daemon
  systemd:
    name: motioneye
    daemon_reload: yes
    state: restarted
    enabled: yes
  become: yes
  ignore_errors: yes